FROM nginx:alpine

# Copiar archivos estáticos
COPY dist/ /usr/share/nginx/html/

# Copiar configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/

# Exponer el puerto 80
EXPOSE 80

# Iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
